Add New Folder contextual menu button
g-leclaire/atom pull request #3
Opened 2018-04-10 20:20 UTC by svhuynh

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

Under the 'File' contextual menu, it is currently possible to create a new file using the 'New File' button. However, it is not possible to create a folder. The following changes enables folder creation within a specified directory, similarly to file creation. This facilitates folder creation, instead using the 'explorer' side-bar. 

![image](https://user-images.githubusercontent.com/31966389/38581015-8a94c750-3cd9-11e8-8d28-4d5c14819cb8.png)

### Alternate Designs

The button can be placed under other contextual menus, but the 'File' menu makes most sense, since 'New File' is under 'File' menu

### Why Should This Be In Core?

This quality of life change facilitates folder creation in all cases.

### Benefits

Faster folder creation

### Possible Drawbacks

None
### Verification Process

I manually created a folder using the new button. I then checked if the folder was created with the right name, at the right directory

### Applicable Issues

https://github.com/g-leclaire/atom/issues/2

2018-04-10 20:54 UTC, g-leclaire requested changes
This is great. However every code change should be accompanied by unit tests. Please address this before the pull request can be approved.

2018-04-10 21:26 UTC, svhuynh commented
Unit tests have been added to the PR.

2018-04-10 21:38 UTC, g-leclaire approved these changes

2018-04-10 23:29 UTC, s-v-huynh approved these changes

2018-04-11 00:11 UTC, svhuynh commented
I have made a few changes fixing the CI build.

2018-04-11 00:16 UTC, havod approved these changes

2018-04-12 15:13 UTC, merged